---

splits:
 train: 100
 valid: 10
 test: 10

output_dir: dataset

labels_seg_dir: labels
labels_det_dir: labels_det

category_names_file: ./dataset/class.names
test_output_dir: ./runs/exp

image_dir: ./dataset/{split}/images
# various output formats selection:
#  1. coco like labels format. Dataset entries are defined by a json file:
coco_detection_dataset_labels_path: ./dataset/{split}/images/annotations.json
# 2. detection label text file per an image, a row for object
detection_label_text_files_path: ./dataset/{split}/labels_det
# 3. detection label text file per all images, a row per image:
detection_label_unified_file_path: ./dataset/{split}/all_entries.txt
# 4. segmentation label text file per an image, a row for object
segmentation_label_files_path: ./dataset/{split}/labels
