---


min_objects_in_image: 3
max_objects_in_image: 3

bg_color: black
# min margin between objects and image edged in pixels:
margin_from_edge: 8
# margin betweem bbox and shape - in pixels:
bbox_margin: 5
# fluctuations of object size:
size_fluctuation: 0.00
# max permited objects overlap. iou=0 means no overlap
iou_thresh: 0

# Notes:
# supported shapes: circle, triangle, ellipse, square, trapezoid, rectangle, hexagon rhombus
# color field is used for class labeling in 'color' or 'color' and 'shape' mode.


# randomly rotate shapes by n*pi/4:
rotate_shapes: true # boolean
# image_size random selection:
image_size: [[640, 640], [960, 800], [600, 800], [1000, 800]]

# note: cnam eorder determines category id assignemt. In case of cname dups, first cname row is taken:
shapes_categories:
  # nvertices: nvertices of polygon. determines the actual shape
  # aspect_ratio: w/h. random selection from list. set 1 one for square &circle, otherwise-rectangle and ellipse
  # theta0: angle of first vertice wrt shape center. e.g for rectangular theta0 must be 45, otherwise rhombus results
  # cname: name label, but actual shape determined by nvertices
  # color: str. random selection from list.
  # height: shape height in pixels. random selection from list. shape width = height / aspect_ratio
  # active: bool. determines row inclusion in dataset generation. Related cname is included class.names and id is assigned anyway.

  [
    { nvertices: 4, theta0: 0, cname: square, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 1 ], active: True},
    { nvertices: 3, theta0: 0, cname: triangle, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 1 ], active: True},
    { nvertices: 80, theta0: 0, cname: circle, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 1 ], active: True}   ,
    { nvertices: 5, theta0: 0, cname: pentagon, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 1 ], active: True},
    { nvertices: 80, theta0: 0, cname: ellipse, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 0.5, 2 ], active: True},
    { nvertices: 6, theta0: 0, cname: hexagon, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 1 ], active: True },
    { nvertices: 4, theta0: 0, cname: rhombus, color: [ red ], height: [ 60, 120 ], aspect_ratio: [ 2, 0.5 ], active: True},
    { nvertices: 4, theta0: 45, cname: rectangular, color: [ red ], height: [60, 120], aspect_ratio:[ 0.5,2 ], active: True},
  ]

